name: GitHub Actions Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    name: GitHub Task Job
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Display GITHUB_ACTIONS environment variable
      - name: Display environment variable
        run: |
          echo "GITHUB_ACTIONS = $GITHUB_ACTIONS"
          echo "Environment variable value: $GITHUB_ACTIONS"
      
      # Step 3: Show branch and repository info
      - name: Display branch and repository
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Branch: $GITHUB_REF_NAME"
          echo "Triggered by: $GITHUB_ACTOR"
      
      # Step 4: Show triggering event
      - name: Display triggering event
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Workflow: $GITHUB_WORKFLOW"
      
      # Step 5: Success message
      - name: Completion message
        run: echo "✅ Workflow executed successfully!"
